version: '3'
services:
  uaa:
    image: shinyay/uaa:latest
    container_name: uaa
    expose:
      - "8090"
    ports:
      - "8090:8090"
  secured-service:
    image: shinyay/spring-cloud-security-service-gs:latest
    container_name: resource
    expose:
      - "9000"
  gateway:
    image: shinyay/spring-cloud-security-gateway-gs:latest
    container_name: gateway
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - secured-service
      - uaa